#!/usr/bin/env python3
"""Builds every Saatbashi logo file from one geometry, so web and Android never drift apart.

The mark: a plain golden clock, a ring and two hands at ten past ten, on a night-sky tile. The
sa'at-bashi was the person who kept the hours and announced the times of prayer.

Run from the repository root:  python3 branding/generate.py
Vector outputs are written directly. PNGs are rasterised from the SVG with Chromium; see
branding/README.md for that step.
"""
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Geometry in a 100x100 box.
CX, CY = 50, 50
RING_R, RING_W = 29, 7
HANDS = [(-60, 14), (60, 20)]  # (angle from twelve in degrees, length): ten past ten
HAND_W = 7

SKY = ("#1a1446", "#20307e", "#2448c9")
GOLD = ("#ffe7ad", "#ffc45c")


def _n(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def T(x, y, s, ox, oy):
    return x * s + ox, y * s + oy


def ring(s=1.0, ox=0.0, oy=0.0):
    """The dial as a closed stroke path (two half arcs)."""
    r = RING_R * s
    x, y = T(CX, CY, s, ox, oy)
    return f"M{_n(x - r)},{_n(y)} A{_n(r)},{_n(r)} 0 1,1 {_n(x + r)},{_n(y)} A{_n(r)},{_n(r)} 0 1,1 {_n(x - r)},{_n(y)} Z"


def hands(s=1.0, ox=0.0, oy=0.0):
    x0, y0 = T(CX, CY, s, ox, oy)
    out = []
    for angle, length in HANDS:
        a = math.radians(angle)
        x1, y1 = T(CX + length * math.sin(a), CY - length * math.cos(a), s, ox, oy)
        out.append(f"M{_n(x0)},{_n(y0)} L{_n(x1)},{_n(y1)}")
    return " ".join(out)


def tile_svg(size=512, radius=116):
    s = size / 100
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">
  <title>ساعت‌باشی</title>
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="{SKY[0]}"/>
      <stop offset="0.55" stop-color="{SKY[1]}"/>
      <stop offset="1" stop-color="{SKY[2]}"/>
    </linearGradient>
    <linearGradient id="gold" x1="0" y1="0" x2="0.4" y2="1">
      <stop offset="0" stop-color="{GOLD[0]}"/>
      <stop offset="1" stop-color="{GOLD[1]}"/>
    </linearGradient>
  </defs>
  <rect width="{size}" height="{size}" rx="{radius}" fill="url(#sky)"/>
  <path d="{ring(s)}" fill="none" stroke="url(#gold)" stroke-width="{_n(RING_W * s)}"/>
  <path d="{hands(s)}" fill="none" stroke="{GOLD[0]}" stroke-width="{_n(HAND_W * s)}" stroke-linecap="round"/>
</svg>
'''


# Android adaptive icon: a 108dp canvas whose inner 66dp circle is always visible.
ANDROID_SCALE = 0.95
CONTENT_CENTRE = (CX, CY)
OX = 54 - CONTENT_CENTRE[0] * ANDROID_SCALE
OY = 54 - CONTENT_CENTRE[1] * ANDROID_SCALE


def _vector(body, extra_ns=False):
    ns = ' xmlns:aapt="http://schemas.android.com/aapt"' if extra_ns else ""
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by branding/generate.py; edit the geometry there, not here. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"{ns}
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
{body}
</vector>
'''


def android_background():
    return _vector(f'''    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108">
                <item android:offset="0" android:color="{SKY[0].upper()}" />
                <item android:offset="0.55" android:color="{SKY[1].upper()}" />
                <item android:offset="1" android:color="{SKY[2].upper()}" />
            </gradient>
        </aapt:attr>
    </path>''', extra_ns=True)


def android_foreground(monochrome=False):
    sc, ox, oy = ANDROID_SCALE, OX, OY
    light = "#FFFFFFFF" if monochrome else GOLD[0].upper()
    ring_colour = light if monochrome else "#FFD27A"
    body = f'''    <path
        android:strokeColor="{ring_colour}"
        android:strokeWidth="{_n(RING_W * sc)}"
        android:pathData="{ring(sc, ox, oy)}" />
    <path
        android:strokeColor="{light}"
        android:strokeWidth="{_n(HAND_W * sc)}"
        android:strokeLineCap="round"
        android:pathData="{hands(sc, ox, oy)}" />'''
    return _vector(body)


def main():
    outputs = {
        "branding/logo.svg": tile_svg(),
        "web/public/favicon.svg": tile_svg(),
        "app/src/main/res/drawable/ic_launcher_background.xml": android_background(),
        "app/src/main/res/drawable/ic_launcher_foreground.xml": android_foreground(),
        "app/src/main/res/drawable/ic_launcher_monochrome.xml": android_foreground(monochrome=True),
    }
    for rel, text in outputs.items():
        (ROOT / rel).write_text(text, encoding="utf-8")
        print("wrote", rel)


if __name__ == "__main__":
    main()
