#!/usr/bin/env python3
"""Writes the occasion tables for web and Android from data/occasions/iran.json, so both stay identical."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CALENDARS = {"Persian": "solar", "Hijri": "lunar", "Gregorian": "gregorian"}
RULES = {"simple": "date", "end of month": "monthEnd", "last weekday of month": "lastWeekday", "nth weekday of month": "nthWeekday"}


def load():
    events = json.loads((ROOT / "data/occasions/iran.json").read_text(encoding="utf-8"))["events"]
    rows = []
    for e in events:
        rows.append({
            "calendar": CALENDARS[e["calendar"]],
            "rule": RULES[e["rule"]],
            "month": e["month"],
            "day": e.get("day", 0),
            "weekday": e.get("weekday", -1),  # Saturday = 0 .. Friday = 6
            "nth": e.get("nth", 0),
            "offset": e.get("offset", 0),
            "holiday": e["holiday"],
            "title": e["title"],
        })
    return rows


HEADER = "Generated by data/occasions/generate.py from data/occasions/iran.json; do not edit by hand."


def web(rows):
    lines = [f"// {HEADER}", "", "import type { OccasionRule } from './occasions';", "", "export const occasionRules: OccasionRule[] = ["]
    for r in rows:
        lines.append(
            f"  [{json.dumps(r['calendar'])}, {json.dumps(r['rule'])}, {r['month']}, {r['day']}, {r['weekday']}, "
            f"{r['nth']}, {r['offset']}, {str(r['holiday']).lower()}, {json.dumps(r['title'], ensure_ascii=False)}],"
        )
    lines += ["];", ""]
    return "\n".join(lines)


def kotlin(rows):
    cal = {"solar": "OccasionCalendar.SOLAR", "lunar": "OccasionCalendar.LUNAR", "gregorian": "OccasionCalendar.GREGORIAN"}
    rule = {"date": "Rule.DATE", "monthEnd": "Rule.MONTH_END", "lastWeekday": "Rule.LAST_WEEKDAY", "nthWeekday": "Rule.NTH_WEEKDAY"}
    lines = [f"// {HEADER}", "", "package ir.mhdolatabadi.atid.data", "", "import ir.mhdolatabadi.atid.data.OccasionRule.Rule", "", "internal val occasionRules: List<OccasionRule> = listOf("]
    for r in rows:
        title = r["title"].replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
        lines.append(
            f"    OccasionRule({cal[r['calendar']]}, {rule[r['rule']]}, {r['month']}, {r['day']}, {r['weekday']}, "
            f"{r['nth']}, {r['offset']}, {str(r['holiday']).lower()}, \"{title}\"),"
        )
    lines += [")", ""]
    return "\n".join(lines)


def main():
    rows = load()
    (ROOT / "web/src/data/occasionsData.ts").write_text(web(rows), encoding="utf-8")
    (ROOT / "app/src/main/java/ir/mhdolatabadi/atid/data/OccasionsData.kt").write_text(kotlin(rows), encoding="utf-8")
    print(f"wrote {len(rows)} occasions for web and Android")


if __name__ == "__main__":
    main()
